//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int Id { get; set; }
        public Nullable<int> id_arenda { get; set; }
        public Nullable<int> id_film { get; set; }
    
        public virtual Arenda Arenda { get; set; }
        public virtual Film Film { get; set; }
    }
}
