//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Zhanr
    {
        public int Id { get; set; }
        public Nullable<int> Id_Film { get; set; }
        public Nullable<int> Id_Zhanr { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Zhanr Zhanr { get; set; }
    }
}
